### ISSUE TITLE
How to use this tools?

### ISSUE THREAD

**Issue by guozanhua** [bmustiata/thriftgen#1]
Hi guy? how to use this tools? Could you give me a example to explain  how to use it?

**Comment by bmustiata** [comment]
_This project is abandoned._ I'm going to update the README to reflect that.

The idea was to load the Thrift service definitions, and generate out of them using HBS the sources for it - currently, Thrift is implemented in C++, and it's a nightmare to change the templates.

You could have a look at the mainapp.py, that was hardcoded to my test file:
https://github.com/bmustiata/thriftgen/blob/master/thriftgen/mainapp.py

The plan was to have it configurable with `click` and whatnot, but I won't use thrift due to tooling.
